servers:
# Shirley2333's server
  shirley: 720649231492186112
  # - 755432126845026365 Emiâ€™s Antisocial CornerğŸ·ğŸ¤ŒğŸ»
# vicçš„æœåŠ¡å™¨
  vic: 925477279142903868
  # - 927926847189159947 Quiet
# DeotherSi9H's playground
  playground: 941248152575541269
  quiet: 927926847189159947